import assert from 'node:assert/strict'
import fs from 'node:fs'
import test from 'node:test'

// 起点源码实扫的六窗十六进制色及 RGBA 精确基色，并集去重；主窗 hex 为 202 色。
const originalHex = [
  '#000', '#b9f0e4', '#ffc0c7', '#f4f8fb', '#8fe0cc', '#fff', '#b489ff', '#152632',
  '#a9dcf4', '#8fb8e0', '#8fd8f0', '#2e2313', '#4a3a22', '#132a1c', '#2b4a37', '#14222c',
  '#6b4f2a', '#241c12', '#6b3038', '#241315', '#e8ca79', '#6b7fb5', '#3d4a6b', '#5a6a9b',
  '#7b3545', '#a9d7ef', '#9fc7ff', '#345477', '#2b3a48', '#1b2530', '#7d92a5', '#0d1318',
  '#b68cff', '#c8a7ff', '#7a4bb5', '#1b2733', '#3f9e63', '#67c98a', '#b8973a', '#e8c66a',
  '#b8703a', '#e8a04c', '#a33448', '#e06c75', '#2a7a9e', '#5ab8d8', '#9ab0c0', '#79c0ea',
  '#7ac9b8', '#e0c27a', '#263645', '#141d25', '#5c2c38', '#321d25', '#17151a', '#302a20',
  '#17191b', '#e8ce9a', '#6a5429', '#c3d1dc', '#16242f', '#162327', '#31584f', '#a9eadb',
  '#162a29', '#ff9cab', '#6b3540', '#e08a97', '#8f75ad', '#c7b3dc', '#9bbbd0', '#2f5f45',
  '#ff8b9a', '#2c5c50', '#5c4a2a', '#2a4a5e', '#172733', '#142b3a', '#d8ad72', '#e7c58d',
  '#2a3742', '#18292c', '#31534e', '#c5f1e7', '#8e3848', '#92702d', '#2f7950', '#ffd1d8',
  '#161d24', '#3a4a58', '#26313c', '#5f8aa8', '#d9b25e', '#6b551f', '#4a5a3a', '#8fd0ff',
  '#28455c', '#66552c', '#1a2530', '#121a22', '#251a20', '#15151b', '#d8b56a', '#294841',
  '#0e1718', '#8f4455', '#c99aa4', '#111b1c', '#f0a0aa', '#9fe0b8', '#0b1116', '#773444',
  '#d66579', '#f1c2ca', '#8fc4e0', '#1b3325', '#33202a', '#2f6b46', '#4a3f22', '#21171c',
  '#d8c890', '#554a28', '#6b3340', '#24475f', '#ffd479', '#1a140d', '#f0dfa0', '#ffa184',
  '#2c4c5c', '#3d2c5c', '#93a4b3', '#2a2417', '#111e27', '#6b592f', '#292414', '#9edbb2',
  '#efd39a', '#142a38', '#d4efff', '#111820', '#d8efff', '#355266', '#9fd8ff', '#13232e',
  '#122633', '#f0c890', '#70512f', '#2a2118', '#101a22', '#ff9bab', '#132430', '#a8ddff',
  '#11231b', '#2a5a70', '#d5f0fa', '#9ad0e0', '#1c3540', '#3a2c44', '#d8b8ff', '#12303c',
  '#4a2830', '#2e2818', '#13251b', '#f1d989', '#fff1b3', '#7fd499', '#e8fff8', '#ff7c8c',
  '#ffe7a0', '#8f7633', '#342d18', '#ffd1d6', '#9b3e4a', '#401820', '#9fd8ae', '#2f6b45',
  '#12271b', '#0f231d', '#3a1c31', '#f0d685', '#ffabb4', '#71323b', '#33121b', '#ffb3bd',
  '#28583a', '#93ddb0', '#ef8b91', '#72b9df', '#7fd4a4', '#d8bd7a', '#c39be8', '#72d9c3',
  '#75cbd1', '#5c4a7a', '#1a1024', '#241733', '#efe3c2', '#1c2430', '#dff0ff', '#9bd8c4',
  '#d8bd82', '#f0a3b0', '#000000', '#151c23', '#05080b', '#ffffff', '#ff6b81', '#ffb74d',
  '#588bb4', '#e9f3fa', '#e2eef6', '#59bca6', '#060a0e', '#aa7430', '#7896dc', '#5cbeaa',
  '#091416', '#070e11', '#78a05a', '#6ee7ff', '#e0a94a', '#120f13', '#080c10', '#4db8ff',
  '#58bda8', '#378f7c', '#12181e', '#14161c', '#3d9e63', '#101814', '#a8f5dc', '#16221f',
  '#1a141c', '#f5d577', '#ff677a', '#ff6377', '#ff5c71', '#ff6f80', '#60c784', '#d4fff0',
  '#ffe0f3', '#64cd8b', '#080e12', '#419ecb', '#4db591', '#c9a159', '#d2576b', '#7ea6cc',
  '#7a869a', '#111920', '#152c3a', '#b9dfff', '#152b39', '#bfe6ff', '#183547', '#6c8291',
  '#263744', '#efab30', '#1b2937', '#2a1a20',
]

// 每枚新 token 的原值与语义基色；同值不表示同职。
const addedTokens = {
  'on-accent': ['#fff', 'fixed'],
  'game-bg': ['#000', 'fixed'],
  'ink': ['#0d1318', 'ink'],
  'eqbg-default': ['#9ab0c0', 'fixed'],
  'eqbg-gun': ['#79c0ea', 'fixed'],
  'eqbg-rdr': ['#7ac9b8', 'fixed'],
  'eqbg-rec': ['#e0c27a', 'fixed'],
  'eqbg-tpb': ['#8fb8e0', 'fixed'],
  'text-soft': ['#c3d1dc', 'text'],
  'accent-soft': ['#9ad0e0', 'accent'],
  'ok-soft': ['#9fe0b8', 'ok'],
  'bad-soft': ['#f0a0aa', 'bad'],
  'night-soft': ['#d8b8ff', 'night'],
  'item-soft': ['#e8ce9a', 'entity-item'],
  'gold-soft': ['#e8ca79', 'gold'],
  'teal-soft': ['#8fd8f0', 'dock'],
  'tint-abyss-line': ['#5c2c38', 'entity-abyss'],
  'tint-abyss-active-line': ['#7b3545', 'entity-abyss'],
  'tint-ok-line': ['#2b4a37', 'ok'],
  'tint-warn-line': ['#6b4f2a', 'warn'],
  'tint-gold-line': ['#4a3f22', 'gold'],
  'tint-ok': ['#132a1c', 'ok'],
  'tint-warn-muted-line': ['#4a3a22', 'warn'],
  'tint-accent-line': ['#2a4a5e', 'accent'],
  'tint-warn': ['#2e2313', 'warn'],
  'tint-ok-active-line': ['#2f5f45', 'ok'],
  'tint-accent': ['#142b3a', 'accent'],
  'badge-complete': ['#f0dfa0', 'gold'],
  'tint-teal-line': ['#2a5a70', 'dock'],
  'tint-accent-compact': ['#152632', 'accent'],
  'tint-accent-filter': ['#14222c', 'accent'],
  'portrait-surface': ['#2b3a48', 'surface'],
  'portrait-soft': ['#7d92a5', 'text'],
  'meter-ok-start': ['#3f9e63', 'ok'],
  'meter-gold-start': ['#b8973a', 'gold'],
  'meter-bad-start': ['#a33448', 'bad'],
  'tint-item-line': ['#6a5429', 'entity-item'],
  'tint-accent-highlight': ['#16242f', 'accent'],
  'tint-teal-map': ['#162327', 'dock'],
  'abyss-boss-soft': ['#ff9cab', 'entity-abyss'],
  'tint-accent-hover': ['#172733', 'accent'],
  'meter-gold-count': ['#92702d', 'gold'],
  'tint-gold-claim-line': ['#6b551f', 'gold'],
  'accent-type-soft': ['#8fd0ff', 'accent'],
  'tint-accent-type-line': ['#28455c', 'accent'],
  'tint-abyss-art-line': ['#8f4455', 'entity-abyss'],
  'tint-accent-fleet-line': ['#24475f', 'accent'],
  'tint-accent-current': ['#142a38', 'accent'],
  'tint-accent-tree-line': ['#355266', 'accent'],
  'accent-tree-soft': ['#9fd8ff', 'accent'],
  'tint-accent-tree': ['#13232e', 'accent'],
  'warn-paused-soft': ['#f0c890', 'warn'],
  'tint-warn-paused-line': ['#70512f', 'warn'],
  'tint-warn-paused': ['#2a2118', 'warn'],
  'teal-selected-soft': ['#d5f0fa', 'dock'],
  'tint-night': ['#3a2c44', 'night'],
  'tint-teal': ['#12303c', 'dock'],
  'tint-bad-line': ['#4a2830', 'bad'],
  'tint-gold': ['#2e2818', 'gold'],
  'bad-banner-soft': ['#ffabb4', 'bad'],
  'tint-bad-deep': ['#33121b', 'bad'],
  'bad-critical-soft': ['#ffb3bd', 'bad'],
  'tint-night-current': ['#241733', 'night'],
  'voice-friendly-soft': ['#b9f0e4', 'r-repair'],
  'voice-enemy-soft': ['#ffc0c7', 'bad'],
  'subtitle-soft': ['#f4f8fb', 'text'],
  'subtitle-speaker-soft': ['#8fe0cc', 'r-repair'],
  'accent-sortie-soft': ['#a9dcf4', 'accent'],
  'tint-warn-chip': ['#241c12', 'warn'],
  'tint-bad-chip-line': ['#6b3038', 'bad'],
  'tint-bad': ['#241315', 'bad'],
  'sandbox-marker': ['#6b7fb5', 'night'],
  'tint-night-sandbox-line': ['#3d4a6b', 'night'],
  'tint-night-hover-line': ['#5a6a9b', 'night'],
  'accent-airbase-soft': ['#a9d7ef', 'accent'],
  'accent-defense-soft': ['#9fc7ff', 'accent'],
  'tint-accent-defense-line': ['#345477', 'accent'],
  'tint-night-attack-line': ['#b68cff', 'night'],
  'night-attack-soft': ['#c8a7ff', 'night'],
  'tint-night-attack': ['#7a4bb5', 'night'],
  'meter-warn-start': ['#b8703a', 'warn'],
  'meter-teal-start': ['#2a7a9e', 'dock'],
  'thumbnail-surface': ['#263645', 'surface'],
  'tint-abyss-thumbnail': ['#321d25', 'entity-abyss'],
  'tint-item': ['#302a20', 'entity-item'],
  'tint-teal-code-line': ['#31584f', 'dock'],
  'teal-code-soft': ['#a9eadb', 'dock'],
  'tint-teal-code': ['#162a29', 'dock'],
  'tint-abyss-boss-line': ['#6b3540', 'entity-abyss'],
  'tint-night-forecast-line': ['#8f75ad', 'night'],
  'night-model-soft': ['#c7b3dc', 'night'],
  'accent-model-soft': ['#9bbbd0', 'accent'],
  'abyss-kill-soft': ['#ff8b9a', 'entity-abyss'],
  'tint-teal-done-line': ['#2c5c50', 'r-repair'],
  'tint-warn-short-line': ['#5c4a2a', 'warn'],
  'warn-missing-soft': ['#d8ad72', 'warn'],
  'warn-dismiss-soft': ['#e7c58d', 'warn'],
  'tint-teal-face-line': ['#31534e', 'dock'],
  'map-code-soft': ['#c5f1e7', 'dock'],
  'meter-abyss': ['#8e3848', 'entity-abyss'],
  'meter-ok-done': ['#2f7950', 'ok'],
  'abyss-gauge-soft': ['#ffd1d8', 'entity-abyss'],
  'ghost-surface': ['#161d24', 'surface'],
  'ghost-line': ['#26313c', 'surface'],
  'disabled-soft': ['#3a4a58', 'text'],
  'ghost-once-soft': ['#5f8aa8', 'accent'],
  'gold-tag-soft': ['#d9b25e', 'gold'],
  'tint-ok-hunt-line': ['#4a5a3a', 'ok'],
  'tint-gold-favorite-line': ['#66552c', 'gold'],
  'item-year-soft': ['#d8b56a', 'entity-item'],
  'tint-teal-art-line': ['#294841', 'dock'],
  'tint-teal-art': ['#0e1718', 'dock'],
  'tint-abyss-art': ['#251a20', 'entity-abyss'],
  'abyss-caption-soft': ['#c99aa4', 'entity-abyss'],
  'tint-teal-minimap': ['#111b1c', 'dock'],
  'gallery-surface': ['#0b1116', 'surface'],
  'meter-abyss-start': ['#773444', 'entity-abyss'],
  'abyss-stat-soft': ['#f1c2ca', 'entity-abyss'],
  'accent-category-soft': ['#8fc4e0', 'accent'],
  'tint-ok-node': ['#1b3325', 'ok'],
  'tint-bad-node': ['#33202a', 'bad'],
  'tint-ok-open-line': ['#2f6b46', 'ok'],
  'tint-abyss-loss': ['#21171c', 'entity-abyss'],
  'item-history-soft': ['#d8c890', 'entity-item'],
  'tint-item-history-line': ['#554a28', 'entity-item'],
  'tint-abyss-history-line': ['#6b3340', 'entity-abyss'],
  'gold-star-soft': ['#ffd479', 'gold'],
  'ink-sortie': ['#1a140d', 'ink'],
  'equip-fire-mark': ['#ffa184', 'warn'],
  'expedition-soft': ['#5ab8d8', 'dock'],
  'tint-teal-period-line': ['#2c4c5c', 'dock'],
  'tint-night-period-line': ['#3d2c5c', 'night'],
  'tint-gold-annual': ['#2a2417', 'gold'],
  'tint-accent-advice': ['#111e27', 'accent'],
  'tint-gold-recommend-line': ['#6b592f', 'gold'],
  'tint-gold-recommend': ['#292414', 'gold'],
  'ok-chain-soft': ['#9edbb2', 'ok'],
  'gold-chain-soft': ['#efd39a', 'gold'],
  'accent-chain-soft': ['#d4efff', 'accent'],
  'ink-claim': ['#111820', 'ink'],
  'accent-quick-soft': ['#d8efff', 'accent'],
  'tint-accent-selected': ['#122633', 'accent'],
  'drawer-heading-surface': ['#101a22', 'surface'],
  'bad-close-soft': ['#ff9bab', 'bad'],
  'tint-accent-system': ['#132430', 'accent'],
  'accent-system-soft': ['#a8ddff', 'accent'],
  'tint-ok-reward': ['#11231b', 'ok'],
  'tint-teal-id': ['#1c3540', 'dock'],
  'tint-ok-net': ['#13251b', 'ok'],
  'gold-banner-edge': ['#f1d989', 'gold'],
  'repair-banner-edge': ['#7fd499', 'ok'],
  'goddess-banner-edge': ['#e8fff8', 'damecon-goddess'],
  'danger-banner-edge': ['#ff7c8c', 'bad'],
  'gold-mark-soft': ['#ffe7a0', 'gold'],
  'tint-gold-mark-line': ['#8f7633', 'gold'],
  'tint-gold-mark': ['#342d18', 'gold'],
  'bad-mark-soft': ['#ffd1d6', 'bad'],
  'tint-bad-mark-line': ['#9b3e4a', 'bad'],
  'tint-bad-mark': ['#401820', 'bad'],
  'ok-mark-soft': ['#9fd8ae', 'ok'],
  'tint-ok-mark-line': ['#2f6b45', 'ok'],
  'tint-ok-mark': ['#12271b', 'ok'],
  'ink-goddess': ['#0f231d', 'ink'],
  'tint-wedding-mark': ['#3a1c31', 'wedding'],
  'gold-banner-soft': ['#f0d685', 'gold'],
  'tint-bad-close-line': ['#71323b', 'bad'],
  'tint-ok-powerup-line': ['#28583a', 'ok'],
  'ok-powerup-soft': ['#93ddb0', 'ok'],
  'gain-fire-soft': ['#ef8b91', 'bad'],
  'gain-torp-soft': ['#72b9df', 'accent'],
  'gain-aa-soft': ['#7fd4a4', 'ok'],
  'gain-armor-soft': ['#d8bd7a', 'gold'],
  'gain-luck-soft': ['#c39be8', 'night'],
  'gain-hp-soft': ['#72d9c3', 'r-repair'],
  'gain-asw-soft': ['#75cbd1', 'dock'],
  'tint-night-event-line': ['#5c4a7a', 'night'],
  'ink-event': ['#1a1024', 'ink'],
  'item-reward-soft': ['#efe3c2', 'entity-item'],
  'event-locked-surface': ['#1c2430', 'surface'],
  'toggle-knob': ['#dff0ff', 'accent'],
  'ok-status-soft': ['#9bd8c4', 'ok'],
  'warn-status-soft': ['#d8bd82', 'warn'],
  'bad-status-soft': ['#f0a3b0', 'bad'],
  'event-soft': ['#b489ff', 'night'],
  'inspector-surface': ['#111820', 'surface'],
  'portrait-surface-deep': ['#1b2530', 'surface'],
  'thumbnail-surface-deep': ['#141d25', 'surface'],
  'tint-abyss-thumbnail-deep': ['#17151a', 'entity-abyss'],
  'tint-item-deep': ['#17191b', 'entity-item'],
  'tint-teal-face': ['#18292c', 'dock'],
  'gallery-card-surface': ['#1a2530', 'surface'],
  'gallery-card-surface-deep': ['#121a22', 'surface'],
  'tint-abyss-art-deep': ['#15151b', 'entity-abyss'],
  'meter-abyss-end': ['#d66579', 'entity-abyss'],
  'gold-banner-highlight': ['#fff1b3', 'gold'],
  'tree-filter-surface': ['#111920', 'surface'],
  'tint-accent-tree-selected': ['#152c3a', 'accent'],
  'accent-relation-soft': ['#b9dfff', 'accent'],
  'tint-accent-open': ['#152b39', 'accent'],
  'accent-ink': ['#bfe6ff', 'accent'],
  'tint-accent-open-hover': ['#183547', 'accent'],
  'chart-axis-soft': ['#6c8291', 'text'],
  'chart-grid-line': ['#263744', 'surface'],
  'life-hero-surface': ['#1b2937', 'surface'],
  'tint-abyss-kill': ['#2a1a20', 'entity-abyss'],
  'shade-overlay': ['#05080b', 'fixed'],
  'glow-abyss': ['#ff6b81', 'entity-abyss'],
  'tint-warn-hurt': ['#ffb74d', 'warn'],
  'tint-accent-airbase': ['#588bb4', 'accent'],
  'glow-shatter': ['#e9f3fa', 'text'],
  'shatter-strike-soft': ['#e2eef6', 'text'],
  'tint-teal-personal': ['#59bca6', 'dock'],
  'shade-detail': ['#060a0e', 'fixed'],
  'tint-warn-missing': ['#aa7430', 'warn'],
  'tint-accent-suggestion': ['#7896dc', 'accent'],
  'glow-map-face': ['#5cbeaa', 'dock'],
  'shade-map-code': ['#091416', 'fixed'],
  'shade-map-gauge': ['#070e11', 'fixed'],
  'tint-ok-hunt': ['#78a05a', 'ok'],
  'glow-gallery': ['#6ee7ff', 'accent'],
  'glow-item': ['#e0a94a', 'entity-item'],
  'shade-abyss-caption': ['#120f13', 'fixed'],
  'shade-gallery': ['#080c10', 'fixed'],
  'tint-teal-net-line': ['#58bda8', 'r-repair'],
  'tint-teal-net': ['#378f7c', 'r-repair'],
  'shade-banner': ['#12181e', 'fixed'],
  'shade-banner-danger': ['#14161c', 'fixed'],
  'shade-banner-repair': ['#101814', 'fixed'],
  'shade-banner-goddess': ['#16221f', 'fixed'],
  'shade-banner-wedding': ['#1a141c', 'fixed'],
  'glow-gold': ['#f5d577', 'gold'],
  'glow-danger-edge': ['#ff677a', 'bad'],
  'glow-danger-pulse': ['#ff6377', 'bad'],
  'glow-danger-frame': ['#ff5c71', 'bad'],
  'glow-danger-border': ['#ff6f80', 'bad'],
  'glow-repair-frame': ['#60c784', 'ok'],
  'glow-goddess-frame': ['#d4fff0', 'damecon-goddess'],
  'glow-powerup': ['#64cd8b', 'ok'],
  'shade-powerup-stat': ['#080e12', 'fixed'],
  'glow-audio-slider': ['#419ecb', 'accent'],
  'tint-ok-status-line': ['#4db591', 'ok'],
  'tint-warn-status-line': ['#c9a159', 'warn'],
  'tint-bad-status-line': ['#d2576b', 'bad'],
  'tint-accent-secretary-line': ['#7ea6cc', 'accent'],
  'secretary-unknown-line': ['#7a869a', 'surface'],
  'browser-surface': ['#fff', 'fixed'],
  'air-marker': ['#8fb8e0', 'accent'],
  'tint-abyss': ['#5c2c38', 'entity-abyss'],
  'meter-ok-muted': ['#2b4a37', 'ok'],
  'danger-banner-highlight': ['#ffc0c7', 'bad'],
}

const addedByFile = {
  "index": [
    "game-bg",
    "voice-friendly-soft",
    "voice-enemy-soft",
    "subtitle-soft",
    "subtitle-speaker-soft",
    "on-accent",
    "event-soft",
    "tint-accent-compact",
    "shade-overlay",
    "accent-sortie-soft",
    "air-marker",
    "teal-soft",
    "tint-warn",
    "tint-warn-muted-line",
    "tint-ok",
    "tint-ok-line",
    "tint-accent-filter",
    "tint-warn-line",
    "tint-warn-chip",
    "tint-bad-chip-line",
    "tint-bad",
    "gold-soft",
    "sandbox-marker",
    "tint-night-sandbox-line",
    "tint-night-hover-line",
    "tint-abyss-active-line",
    "glow-abyss",
    "tint-warn-hurt",
    "tint-accent-airbase",
    "accent-airbase-soft",
    "accent-defense-soft",
    "tint-accent-defense-line",
    "glow-shatter",
    "shatter-strike-soft",
    "portrait-surface",
    "portrait-surface-deep",
    "portrait-soft",
    "ink",
    "tint-night-attack-line",
    "night-attack-soft",
    "tint-night-attack",
    "meter-ok-start",
    "meter-gold-start",
    "meter-warn-start",
    "meter-bad-start",
    "meter-teal-start",
    "expedition-soft",
    "eqbg-default",
    "eqbg-gun",
    "eqbg-tpb",
    "eqbg-rdr",
    "eqbg-rec",
    "thumbnail-surface",
    "thumbnail-surface-deep",
    "tint-abyss-line",
    "tint-abyss-thumbnail",
    "tint-abyss-thumbnail-deep",
    "tint-item",
    "tint-item-deep",
    "item-soft",
    "tint-item-line",
    "text-soft",
    "tint-accent-highlight",
    "tint-teal-map",
    "tint-teal-code-line",
    "teal-code-soft",
    "tint-teal-code",
    "tint-teal-personal",
    "abyss-boss-soft",
    "tint-abyss-boss-line",
    "tint-night-forecast-line",
    "night-model-soft",
    "accent-model-soft",
    "tint-ok-active-line",
    "abyss-kill-soft",
    "shade-detail",
    "tint-teal-done-line",
    "tint-warn-short-line",
    "tint-accent-line",
    "tint-accent-hover",
    "tint-accent",
    "warn-missing-soft",
    "tint-warn-missing",
    "warn-dismiss-soft",
    "tint-accent-suggestion",
    "tint-teal-face",
    "tint-teal-face-line",
    "glow-map-face",
    "map-code-soft",
    "shade-map-code",
    "shade-map-gauge",
    "meter-abyss",
    "meter-gold-count",
    "meter-ok-done",
    "abyss-gauge-soft",
    "ghost-surface",
    "disabled-soft",
    "ghost-line",
    "ghost-once-soft",
    "gold-tag-soft",
    "tint-gold-claim-line",
    "tint-ok-hunt-line",
    "tint-ok-hunt",
    "glow-gallery",
    "accent-type-soft",
    "tint-accent-type-line",
    "tint-gold-favorite-line",
    "gallery-card-surface",
    "gallery-card-surface-deep",
    "tint-abyss-art",
    "tint-abyss-art-deep",
    "glow-item",
    "item-year-soft",
    "tint-teal-art-line",
    "tint-teal-art",
    "tint-abyss-art-line",
    "shade-abyss-caption",
    "abyss-caption-soft",
    "tint-teal-minimap",
    "bad-soft",
    "ok-soft",
    "gallery-surface",
    "shade-gallery",
    "meter-abyss-start",
    "meter-abyss-end",
    "abyss-stat-soft",
    "tint-abyss",
    "accent-category-soft",
    "tint-ok-node",
    "tint-bad-node",
    "tint-ok-open-line",
    "tint-gold-line",
    "tint-abyss-loss",
    "item-history-soft",
    "tint-item-history-line",
    "tint-abyss-history-line",
    "tint-accent-fleet-line",
    "gold-star-soft",
    "ink-sortie",
    "badge-complete",
    "equip-fire-mark",
    "tint-teal-period-line",
    "tint-night-period-line",
    "tint-gold-annual",
    "tint-accent-advice",
    "tint-gold-recommend-line",
    "tint-gold-recommend",
    "ok-chain-soft",
    "gold-chain-soft",
    "tint-accent-current",
    "accent-chain-soft",
    "ink-claim",
    "accent-quick-soft",
    "tint-accent-tree-line",
    "accent-tree-soft",
    "tint-accent-tree",
    "tint-accent-selected",
    "warn-paused-soft",
    "tint-warn-paused-line",
    "tint-warn-paused",
    "drawer-heading-surface",
    "bad-close-soft",
    "tint-accent-system",
    "accent-system-soft",
    "tint-ok-reward",
    "tint-teal-line",
    "teal-selected-soft",
    "accent-soft",
    "tint-teal-id",
    "tint-night",
    "night-soft",
    "tint-teal",
    "tint-bad-line",
    "tint-gold",
    "tint-ok-net",
    "tint-teal-net-line",
    "tint-teal-net",
    "shade-banner",
    "shade-banner-danger",
    "shade-banner-repair",
    "shade-banner-goddess",
    "shade-banner-wedding",
    "gold-banner-edge",
    "gold-banner-highlight",
    "glow-gold",
    "repair-banner-edge",
    "goddess-banner-edge",
    "danger-banner-edge",
    "danger-banner-highlight",
    "glow-danger-edge",
    "gold-mark-soft",
    "tint-gold-mark-line",
    "tint-gold-mark",
    "bad-mark-soft",
    "tint-bad-mark-line",
    "tint-bad-mark",
    "ok-mark-soft",
    "tint-ok-mark-line",
    "tint-ok-mark",
    "ink-goddess",
    "tint-wedding-mark",
    "gold-banner-soft",
    "bad-banner-soft",
    "tint-bad-close-line",
    "glow-danger-pulse",
    "glow-danger-frame",
    "glow-danger-border",
    "glow-repair-frame",
    "glow-goddess-frame",
    "tint-bad-deep",
    "bad-critical-soft",
    "glow-powerup",
    "tint-ok-powerup-line",
    "ok-powerup-soft",
    "shade-powerup-stat",
    "gain-fire-soft",
    "gain-torp-soft",
    "gain-aa-soft",
    "gain-armor-soft",
    "gain-luck-soft",
    "gain-hp-soft",
    "gain-asw-soft",
    "tint-night-event-line",
    "ink-event",
    "tint-night-current",
    "item-reward-soft",
    "event-locked-surface",
    "meter-ok-muted",
    "glow-audio-slider",
    "toggle-knob",
    "tint-ok-status-line",
    "ok-status-soft",
    "tint-warn-status-line",
    "warn-status-soft",
    "tint-bad-status-line",
    "bad-status-soft",
    "tint-accent-secretary-line",
    "secretary-unknown-line",
    "tree-filter-surface",
    "tint-accent-tree-selected",
    "inspector-surface",
    "accent-relation-soft",
    "tint-accent-open",
    "tint-accent-open-hover",
    "chart-axis-soft",
    "chart-grid-line",
    "life-hero-surface",
    "tint-abyss-kill",
    "browser-surface"
  ],
  "battle-replay": [
    "eqbg-default",
    "ink",
    "eqbg-gun",
    "eqbg-tpb",
    "eqbg-rdr",
    "eqbg-rec",
    "thumbnail-surface",
    "thumbnail-surface-deep",
    "tint-abyss-line",
    "tint-abyss-thumbnail",
    "tint-abyss-thumbnail-deep"
  ],
  "quest-tree": [
    "tree-filter-surface",
    "tint-accent-hover",
    "tint-accent-tree-selected",
    "inspector-surface",
    "accent-relation-soft",
    "tint-accent-open",
    "accent-ink",
    "tint-accent-open-hover"
  ],
  "resource-trend": [
    "on-accent",
    "chart-axis-soft",
    "chart-grid-line"
  ],
  "ship-life": [
    "life-hero-surface",
    "tint-abyss-kill"
  ],
  "browse": [
    "browser-surface"
  ]
}

// 起点 4563a33 的旧 token 名单；语义色与模板色另有逐枚断言，此处覆盖原集合哈希保护的全部项目。
const originalTokenValues = {
  "index": {
    "bg0": "#0d1318",
    "bg1": "#151c23",
    "bg2": "#1c252e",
    "bg3": "#232f3a",
    "line": "#2a3742",
    "line-soft": "#22303c",
    "text": "#e8eef4",
    "sub": "#93a4b3",
    "dim": "#75899a",
    "accent": "#4db8ff",
    "accent-dim": "#2a6f9e",
    "gold": "#e8c66a",
    "ok": "#67c98a",
    "warn": "#e8a04c",
    "bad": "#e06c75",
    "dock": "#48a6c9",
    "r-fuel": "#8fb87a",
    "r-ammo": "#b99a4e",
    "r-steel": "#8fa8c0",
    "r-baux": "#efab30",
    "r-build": "#5f96d3",
    "r-repair": "#7ac9b8",
    "r-dev": "#9d78e5",
    "r-screw": "#e08a97",
    "entity-ship": "#83c9ff",
    "entity-abyss": "#ff8796",
    "entity-equip": "#79d4e8",
    "entity-map": "#86d29b",
    "entity-item": "#e6b98f",
    "entity-quest": "#c9a7ff",
    "entity-expedition": "#e89a82",
    "entity-fleet": "#aab8ff",
    "entity-material": "#b6a47e",
    "entity-practice": "#e2a2d1",
    "entity-timer": "#9fd3c7",
    "entity-nationality": "#b8d27e",
    "entity-shipclass": "#f7bfc6",
    "entity-histfleet": "#5fe0cd",
    "accent-ink": "#bfe6ff",
    "accent-wash": "#173040",
    "abyss-ink": "#ff9fae",
    "abyss-soft": "#e8b8c0",
    "air": "#8fd694",
    "night": "#7e86f2",
    "stat-grow": "#3f9bd8",
    "stat-over99": "#9b7fd4",
    "stat-marriage": "#d98cae",
    "stat-mod": "#c98d4f",
    "stat-equip": "#5cb17e",
    "stat-track": "#1b2733",
    "voice-dmg-light": "#ffe9a0",
    "voice-dmg-mid": "#ffc46b",
    "voice-dmg-heavy": "#ff8585",
    "voice-dmg-sunk": "#c5a3f0",
    "voice-special": "light-dark(#c58b12, #ffdb70)",
    "damecon-crew": "#3d9e63",
    "damecon-goddess": "#a8f5dc",
    "wedding": "#ff8fd6",
    "wedding-rgb": "255, 143, 214",
    "wedding-lit": "#ffe0f3",
    "scrollbar-track": "#10171d",
    "scrollbar-thumb": "#334957",
    "scrollbar-thumb-hover": "#486476",
    "scrollbar-thumb-active": "#5c7b90",
    "motion-fast": "150ms",
    "motion-micro": "120ms",
    "motion-view": "200ms",
    "motion-solemn": "900ms",
    "motion-ease": "cubic-bezier(.2, .72, .22, 1)",
    "serif": "'Yu Mincho', 'MS Mincho', 'SimSun', serif",
    "mono": "'Maple Mono NF CN', 'Cascadia Code', 'Consolas', monospace",
    "sans": "'Segoe UI', 'Microsoft YaHei', sans-serif"
  },
  "battle-replay": {
    "bg0": "#0d1318",
    "bg1": "#151c23",
    "bg2": "#1c252e",
    "bg3": "#232f3a",
    "line": "#2a3742",
    "line-soft": "#22303c",
    "text": "#e8eef4",
    "sub": "#93a4b3",
    "dim": "#75899a",
    "accent": "#4db8ff",
    "accent-dim": "#2a6f9e",
    "accent-ink": "#bfe6ff",
    "accent-wash": "#173040",
    "gold": "#e8c66a",
    "ok": "#67c98a",
    "warn": "#e8a04c",
    "bad": "#e06c75",
    "air": "#8fd694",
    "night": "#7e86f2",
    "abyss-ink": "#ff9fae",
    "entity-ship": "#83c9ff",
    "entity-abyss": "#ff8796",
    "entity-equip": "#79d4e8",
    "entity-map": "#86d29b",
    "r-fuel": "#8fb87a",
    "scrollbar-track": "#10171d",
    "scrollbar-thumb": "#334957",
    "scrollbar-thumb-hover": "#486476",
    "scrollbar-thumb-active": "#5c7b90",
    "motion-fast": "150ms",
    "motion-micro": "120ms",
    "motion-view": "200ms",
    "motion-ease": "cubic-bezier(.2, .72, .22, 1)",
    "serif": "'Yu Mincho', 'MS Mincho', 'SimSun', serif",
    "mono": "'Maple Mono NF CN', 'Cascadia Code', 'Consolas', monospace",
    "sans": "'Segoe UI', 'Microsoft YaHei', sans-serif"
  },
  "quest-tree": {
    "bg0": "#0d1318",
    "bg1": "#151c23",
    "bg2": "#1c252e",
    "bg3": "#232f3a",
    "line": "#2a3742",
    "line-soft": "#22303c",
    "text": "#e8eef4",
    "sub": "#93a4b3",
    "dim": "#5c6f7f",
    "accent": "#4db8ff",
    "accent-dim": "#2a6f9e",
    "gold": "#e8c66a",
    "ok": "#67c98a",
    "warn": "#e8a04c",
    "bad": "#e06c75",
    "scrollbar-track": "#10171d",
    "scrollbar-thumb": "#334957",
    "scrollbar-thumb-hover": "#486476",
    "scrollbar-thumb-active": "#5c7b90",
    "mono": "'Cascadia Code', 'Consolas', monospace"
  },
  "resource-trend": {
    "bg0": "#0d1318",
    "bg1": "#121a21",
    "bg2": "#18232d",
    "bg3": "#20303d",
    "line": "#2a3a47",
    "line-soft": "#202d37",
    "text": "#d8e2e9",
    "sub": "#9eb0bd",
    "dim": "#607583",
    "accent": "#63b6de",
    "accent-dim": "#367c9e",
    "ok": "#67c98a",
    "bad": "#e06c75",
    "gold": "#d5b75e",
    "r-fuel": "#7ecb9a",
    "r-ammo": "#b99a4e",
    "r-steel": "#8fa8c0",
    "r-baux": "#efab30",
    "r-repair": "#7ac9b8",
    "scrollbar-track": "#10171d",
    "scrollbar-thumb": "#334957",
    "scrollbar-thumb-hover": "#486476",
    "scrollbar-thumb-active": "#5c7b90",
    "mono": "'Maple Mono NF CN', 'Cascadia Code', 'Consolas', monospace"
  },
  "ship-life": {
    "bg0": "#0d1318",
    "bg1": "#151c23",
    "bg2": "#1c252e",
    "bg3": "#232f3a",
    "line": "#2a3742",
    "line-soft": "#22303c",
    "text": "#e8eef4",
    "sub": "#93a4b3",
    "dim": "#75899a",
    "accent": "#4db8ff",
    "accent-dim": "#2a6f9e",
    "accent-ink": "#bfe6ff",
    "gold": "#e8c66a",
    "ok": "#67c98a",
    "warn": "#e8a04c",
    "bad": "#e06c75",
    "dock": "#48a6c9",
    "wedding": "#ff8fd6",
    "abyss-ink": "#ff9fae",
    "entity-map": "#86d29b",
    "scrollbar-track": "#10171d",
    "scrollbar-thumb": "#334957",
    "scrollbar-thumb-hover": "#486476",
    "scrollbar-thumb-active": "#5c7b90",
    "mono": "'Cascadia Code', 'Consolas', monospace",
    "serif": "'Source Han Serif SC', 'Noto Serif CJK SC', 'Songti SC', serif"
  },
  "browse": {
    "bg0": "#0d1318",
    "bg1": "#121a21",
    "bg2": "#18232d",
    "bg3": "#20303d",
    "line": "#2a3a47",
    "line-soft": "#202d37",
    "text": "#d8e2e9",
    "sub": "#9eb0bd",
    "dim": "#607583",
    "accent": "#63b6de",
    "accent-dim": "#367c9e",
    "mono": "'Maple Mono NF CN', 'Cascadia Code', 'Consolas', monospace"
  }
}

const files = ['index', 'battle-replay', 'quest-tree', 'resource-trend', 'ship-life', 'browse']
const read = name => fs.readFileSync(new URL('../src/renderer/' + name + '.html', import.meta.url), 'utf8')
const stripComments = value => value.replace(/\/\*[\s\S]*?\*\//g, '')
const styles = source => [...source.matchAll(/<style[^>]*>([\s\S]*?)<\/style>/g)].map(m => m[1]).join('\n')
const blocks = source => [...styles(source).matchAll(/:root(?:\[data-theme="light"\])?\s*\{([^}]+)\}/g)].map(m => m[1])
const declarations = block => Object.fromEntries([...stripComments(block).matchAll(/--([\w-]+):\s*([^;]+);/g)].map(m => [m[1], m[2].trim()]))
const outsideRoots = source => stripComments(styles(source)).replace(/:root(?:\[data-theme="light"\])?\s*\{[^}]*\}/g, '')
const rgb = hex => {
  let digits = hex.slice(1)
  if (digits.length === 3) digits = [...digits].map(c => c + c).join('')
  return [0, 2, 4].map(i => parseInt(digits.slice(i, i + 2), 16))
}
const toHex = channels => '#' + channels.map(c => Math.round(c).toString(16).padStart(2, '0')).join('')
const luminance = hex => rgb(hex).map(c => {
  c /= 255
  return c <= 0.04045 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4
}).reduce((sum, c, i) => sum + c * [0.2126, 0.7152, 0.0722][i], 0)
const contrast = (a, b) => (Math.max(luminance(a), luminance(b)) + 0.05) / (Math.min(luminance(a), luminance(b)) + 0.05)
// 以下为已退役的一次性整表验收机制记录；常驻检查使用起点 token 名单。
// 展开默认深色变量后，把透明混合还原为同一组 RGBA 数值再比较完整样式表。
// 比「颜色曾出现在清单」更强：换错位置、透明度或渐变任一色标都会改变摘要。
// 浅色专属覆盖不会参与深色级联；仍比较其余全部旧声明。

for (const name of files) {
  test(name + ' 样式声明中不再有根块外十六进制颜色（仅纯黑阴影豁免）', () => {
    const found = []
    for (const rule of outsideRoots(read(name)).matchAll(/([^{}]+)\{([^{}]*)\}/g)) {
      for (const declaration of rule[2].split(';')) {
        const colon = declaration.indexOf(':')
        if (colon < 0) continue
        const property = declaration.slice(0, colon).trim()
        const value = declaration.slice(colon + 1)
        for (const color of value.matchAll(/#[0-9a-fA-F]{3,8}\b/g)) {
          if (/^(text-shadow|box-shadow)$/.test(property) && color[0] === '#000') continue
          found.push(rule[1].trim() + ' / ' + property + ': ' + color[0])
        }
      }
    }
    assert.deepEqual(found, [])
  })

  test(name + ' 新 token 深色逐值等于原清单且浅色完整覆盖', () => {
    const source = read(name)
    const [dark, light] = blocks(source).map(declarations)
    const expected = addedByFile[name]
    const section = blocks(source)[0].split('/* 样式表语义颜色：按使用角色保留各档原值。 */')[1] ?? ''
    assert.deepEqual(Object.keys(declarations(section)).sort(), [...expected].sort())
    assert.equal(originalHex.length, 260)
    assert.equal(new Set(originalHex).size, originalHex.length)
    for (const token of expected) {
      assert.equal(dark[token], addedTokens[token][0], token)
      assert.ok(originalHex.includes(dark[token]), token + ' 不在原清单')
      assert.match(light[token] ?? '', /^#[0-9a-fA-F]{6}$/, token)
    }
    // 42c5469 收编时做过整表展开等值验收（见该单交付记录），常驻护栏改由下面的 token 深色值等值断言承担
  })

  test(name + ' 起点 token 逐枚仍存在且深色值不变，允许新增 token', () => {
    const dark = declarations(blocks(read(name))[0])
    for (const [token, value] of Object.entries(originalTokenValues[name])) {
      assert.ok(Object.hasOwn(dark, token), name + ' 缺少起点 token --' + token)
      assert.equal(dark[token], value, name + ' / --' + token)
    }
  })

  test(name + ' 浅色软文字、状态底与状态边达到对比度约束', () => {
    const light = declarations(blocks(read(name))[1])
    const mainLight = declarations(blocks(read('index'))[1])
    for (const token of addedByFile[name]) {
      const color = light[token]
      const ratio = contrast(color, light.bg1)
      if (token.endsWith('-soft')) assert.ok(ratio >= 4.5, token + ': ' + ratio)
      if (token.startsWith('tint-')) {
        const line = token.endsWith('-line')
        assert.ok(line ? ratio >= 1.3 : ratio <= 1.6, token + ': ' + ratio)
        const weight = line ? 0.4 : 0.18
        const expected = toHex(rgb(mainLight[addedTokens[token][1]]).map(c => c * weight + 255 * (1 - weight)))
        assert.equal(color, expected, token + ' 按固定 sRGB 比例混白')
      }
      if (token.startsWith('glow-')) {
        const expected = toHex(rgb(mainLight[addedTokens[token][1]]).map(c => c * 0.18 + 255 * 0.82))
        assert.equal(color, expected, token + ' 氛围光按所属族混白')
      }
      if (token.startsWith('shade-')) assert.equal(color, addedTokens[token][0], token + ' 暗罩保持深色')
      if (token.startsWith('eqbg-') || token === 'game-bg' || token === 'on-accent') {
        assert.deepEqual(rgb(color), rgb(addedTokens[token][0]), token + ' 固定颜色')
      }
    }
  })

  test(name + ' 剩余 RGBA 只含纯黑阴影或纯白高光基色', () => {
    const remaining = [...outsideRoots(read(name)).matchAll(/rgba\(([^)]*)\)/g)].map(m => m[1])
    const invalid = remaining.filter(value => {
      const parts = value.split(',').map(v => v.trim())
      return parts.length !== 4 || !['0,0,0', '255,255,255'].includes(parts.slice(0, 3).join(','))
    })
    assert.deepEqual(invalid, [])
  })

  // 42c5469 收编时做过整表展开等值验收（见该单交付记录），常驻护栏改由下面的 token 深色值等值断言承担
}
